/*
 * generated by Xtext
 */
package scenario.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScenarioDSLUiModule extends scenario.ui.AbstractScenarioDSLUiModule {
	public ScenarioDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
