/*
 * generated by Xtext
 */
package scenario.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import scenario.services.ScenarioDSLGrammarAccess;

public class ScenarioDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ScenarioDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected scenario.parser.antlr.internal.InternalScenarioDSLParser createParser(XtextTokenStream stream) {
		return new scenario.parser.antlr.internal.InternalScenarioDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Scenario";
	}
	
	public ScenarioDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ScenarioDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
