/*
 * generated by Xtext
 */
package scenario;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ScenarioDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return scenario.ui.internal.ScenarioDSLActivator.getInstance().getInjector("scenario.ScenarioDSL");
	}
	
}
