/**
 * generated by Xtext
 */
package scenario.serializer;

import scenario.serializer.AbstractScenarioDSLSyntacticSequencer;

@SuppressWarnings("all")
public class ScenarioDSLSyntacticSequencer extends AbstractScenarioDSLSyntacticSequencer {
}
