/**
 * generated by Xtext
 */
package scenario.ui.contentassist;

import scenario.ui.contentassist.AbstractScenarioDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ScenarioDSLProposalProvider extends AbstractScenarioDSLProposalProvider {
}
