/*
 * generated by Xtext
 */
package scenario;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ScenarioDSLStandaloneSetup extends ScenarioDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new ScenarioDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

