/*
 * generated by Xtext
 */
package scenario;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScenarioDSLRuntimeModule extends scenario.AbstractScenarioDSLRuntimeModule {

}
