/*
 * generated by Xtext
 */
package scenario;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ScenarioStandaloneSetup extends ScenarioStandaloneSetupGenerated{

	public static void doSetup() {
		new ScenarioStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

