/*
 * generated by Xtext
 */
package scenario.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScenarioUiModule extends scenario.ui.AbstractScenarioUiModule {
	public ScenarioUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
