/**
 * generated by Xtext
 */
package scenario.serializer;

import scenario.serializer.AbstractScenarioDSLSemanticSequencer;

@SuppressWarnings("all")
public class ScenarioDSLSemanticSequencer extends AbstractScenarioDSLSemanticSequencer {
}
