/**
 * generated by Xtext
 */
package scenario.validation;

import scenario.validation.AbstractScenarioDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ScenarioDSLValidator extends AbstractScenarioDSLValidator {
}
