/*
 * generated by Xtext
 */
package scenario.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import scenario.ui.internal.ScenarioDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScenarioDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ScenarioDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ScenarioDSLActivator.getInstance().getInjector(ScenarioDSLActivator.SCENARIO_SCENARIODSL);
	}
	
}
