/**
 * generated by Xtext
 */
package scenario.serializer;

import scenario.serializer.AbstractScenarioSyntacticSequencer;

@SuppressWarnings("all")
public class ScenarioSyntacticSequencer extends AbstractScenarioSyntacticSequencer {
}
