/**
 * generated by Xtext
 */
package scenario.serializer;

import scenario.serializer.AbstractScenarioSemanticSequencer;

@SuppressWarnings("all")
public class ScenarioSemanticSequencer extends AbstractScenarioSemanticSequencer {
}
