print_endline "================================";
print_endline "Tri topologique";
print_endline "================================";
print_endline "dag1";
print_endline "----------------";
tri_topologique dag1;;
print_endline "----------------";
print_endline "dag2";
print_endline "----------------";
tri_topologique dag2;;
print_endline "----------------";
print_endline "dag3";
print_endline "----------------";
tri_topologique dag3;;
print_endline "----------------";
print_endline "dag4";
print_endline "----------------";
tri_topologique dag4;;

print_endline "================================";
print_endline "Ordonnanceur sans heuristique";
print_endline "================================";
print_endline "dag1, r = 2";
print_endline "----------------";
ordonnanceur_sans_heuristique 2 dag1;;
List.length (ordonnanceur_sans_heuristique 2 dag1);;
print_endline "----------------";
print_endline "dag1, r = 4";
print_endline "----------------";
ordonnanceur_sans_heuristique 4 dag1;;
List.length (ordonnanceur_sans_heuristique 4 dag1);;
print_endline "----------------";
print_endline "dag1, r = 6";
print_endline "----------------";
ordonnanceur_sans_heuristique 6 dag1;;
List.length (ordonnanceur_sans_heuristique 6 dag1);;
print_endline "----------------";
print_endline "dag2, r = 2";
print_endline "----------------";
ordonnanceur_sans_heuristique 2 dag2;;
List.length (ordonnanceur_sans_heuristique 2 dag2);;
print_endline "----------------";
print_endline "dag2, r = 4";
print_endline "----------------";
ordonnanceur_sans_heuristique 4 dag2;;
List.length (ordonnanceur_sans_heuristique 4 dag2);;
print_endline "----------------";
print_endline "dag2, r = 6";
print_endline "----------------";
ordonnanceur_sans_heuristique 6 dag2;;
List.length (ordonnanceur_sans_heuristique 6 dag2);;
print_endline "----------------";
print_endline "dag3, r = 2";
print_endline "----------------";
ordonnanceur_sans_heuristique 2 dag3;;
List.length (ordonnanceur_sans_heuristique 2 dag3);;
print_endline "----------------";
print_endline "dag3, r = 4";
print_endline "----------------";
ordonnanceur_sans_heuristique 4 dag3;;
List.length (ordonnanceur_sans_heuristique 4 dag3);;
print_endline "----------------";
print_endline "dag3, r = 6";
print_endline "----------------";
ordonnanceur_sans_heuristique 6 dag3;;
List.length (ordonnanceur_sans_heuristique 6 dag3);;
print_endline "----------------";
print_endline "dag4, r = 2";
print_endline "----------------";
ordonnanceur_sans_heuristique 2 dag4;;
List.length (ordonnanceur_sans_heuristique 2 dag4);;
print_endline "----------------";
print_endline "dag4, r = 4";
print_endline "----------------";
ordonnanceur_sans_heuristique 4 dag4;;
List.length (ordonnanceur_sans_heuristique 4 dag4);;
print_endline "----------------";
print_endline "dag4, r = 6";
print_endline "----------------";
ordonnanceur_sans_heuristique 6 dag4;;
List.length (ordonnanceur_sans_heuristique 6 dag4);;

print_endline "================================";
print_endline "Ordonnanceur avec heuristique";
print_endline "================================";
print_endline "dag1, r = 2";
print_endline "----------------";
ordonnanceur_avec_heuristique 2 dag1;;
List.length (ordonnanceur_avec_heuristique 2 dag1);;
print_endline "----------------";
print_endline "dag1, r = 4";
print_endline "----------------";
ordonnanceur_avec_heuristique 4 dag1;;
List.length (ordonnanceur_avec_heuristique 4 dag1);;
print_endline "----------------";
print_endline "dag1, r = 6";
print_endline "----------------";
ordonnanceur_avec_heuristique 6 dag1;;
List.length (ordonnanceur_avec_heuristique 6 dag1);;
print_endline "----------------";
print_endline "dag2, r = 2";
print_endline "----------------";
ordonnanceur_avec_heuristique 2 dag2;;
List.length (ordonnanceur_avec_heuristique 2 dag2);;
print_endline "----------------";
print_endline "dag2, r = 4";
print_endline "----------------";
ordonnanceur_avec_heuristique 4 dag2;;
List.length (ordonnanceur_avec_heuristique 4 dag2);;
print_endline "----------------";
print_endline "dag2, r = 6";
print_endline "----------------";
ordonnanceur_avec_heuristique 6 dag2;;
List.length (ordonnanceur_avec_heuristique 6 dag2);;
print_endline "----------------";
print_endline "dag3, r = 2";
print_endline "----------------";
ordonnanceur_avec_heuristique 2 dag3;;
List.length (ordonnanceur_avec_heuristique 2 dag3);;
print_endline "----------------";
print_endline "dag3, r = 4";
print_endline "----------------";
ordonnanceur_avec_heuristique 4 dag3;;
List.length (ordonnanceur_avec_heuristique 4 dag3);;
print_endline "----------------";
print_endline "dag3, r = 6";
print_endline "----------------";
ordonnanceur_avec_heuristique 6 dag3;;
List.length (ordonnanceur_avec_heuristique 6 dag3);;
print_endline "----------------";
print_endline "dag4, r = 2";
print_endline "----------------";
ordonnanceur_avec_heuristique 2 dag4;;
List.length (ordonnanceur_avec_heuristique 2 dag4);;
print_endline "----------------";
print_endline "dag4, r = 4";
print_endline "----------------";
ordonnanceur_avec_heuristique 4 dag4;;
List.length (ordonnanceur_avec_heuristique 4 dag4);;
print_endline "----------------";
print_endline "dag4, r = 6";
print_endline "----------------";
ordonnanceur_avec_heuristique 6 dag4;;
List.length (ordonnanceur_avec_heuristique 6 dag4);;

print_endline "================================";
print_endline "Ordonnanceur contraintes mémoire";
print_endline "================================";
print_endline "dag1, r = 3, m = 4";
print_endline "----------------";
ordonnanceur_contrainte_memoire 3 4 dag1;;
List.length (ordonnanceur_contrainte_memoire 3 4 dag1);;
print_endline "----------------";
print_endline "dag1, r = 3, m = 6";
print_endline "----------------";
ordonnanceur_contrainte_memoire 3 6 dag1;;
List.length (ordonnanceur_contrainte_memoire 3 6 dag1);;
print_endline "----------------";
print_endline "dag1, r = 4, m = 5";
print_endline "----------------";
ordonnanceur_contrainte_memoire 4 6 dag1;;
List.length (ordonnanceur_contrainte_memoire 4 6 dag1);;
print_endline "----------------";
print_endline "dag2, r = 3, m = 4";
print_endline "----------------";
ordonnanceur_contrainte_memoire 3 4 dag2;;
List.length (ordonnanceur_contrainte_memoire 3 4 dag2);;
print_endline "----------------";
print_endline "dag2, r = 3, m = 6";
print_endline "----------------";
ordonnanceur_contrainte_memoire 3 6 dag2;;
List.length (ordonnanceur_contrainte_memoire 3 6 dag2);;
print_endline "----------------";
print_endline "dag2, r = 4, m = 6";
print_endline "----------------";
ordonnanceur_contrainte_memoire 4 6 dag2;;
List.length (ordonnanceur_contrainte_memoire 4 6 dag2);;
print_endline "----------------";
print_endline "dag3, r = 3, m = 4";
print_endline "----------------";
ordonnanceur_contrainte_memoire 3 4 dag3;;
List.length (ordonnanceur_contrainte_memoire 3 4 dag3);;
print_endline "----------------";
print_endline "dag3, r = 3, m = 6";
print_endline "----------------";
ordonnanceur_contrainte_memoire 3 6 dag3;;
List.length (ordonnanceur_contrainte_memoire 3 6 dag3);;
print_endline "----------------";
print_endline "dag3, r = 4, m = 6";
print_endline "----------------";
ordonnanceur_contrainte_memoire 4 6 dag3;;
List.length (ordonnanceur_contrainte_memoire 4 6 dag3);;
print_endline "----------------";
print_endline "dag4, r = 3, m = 4";
print_endline "----------------";
ordonnanceur_contrainte_memoire 3 4 dag4;;
List.length (ordonnanceur_contrainte_memoire 3 4 dag4);;
print_endline "----------------";
print_endline "dag4, r = 3, m = 6";
print_endline "----------------";
ordonnanceur_contrainte_memoire 3 6 dag4;;
List.length (ordonnanceur_contrainte_memoire 3 6 dag4);;
print_endline "----------------";
print_endline "dag4, r = 4, m = 6";
print_endline "----------------";
ordonnanceur_contrainte_memoire 4 6 dag4;;
List.length (ordonnanceur_contrainte_memoire 4 6 dag4);;
