/*
 * generated by Xtext
 */
package scenario;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ScenarioUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return scenario.ui.internal.ScenarioActivator.getInstance().getInjector("scenario.Scenario");
	}
	
}
